# Generated by Django 3.0 on 2020-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_link', models.CharField(max_length=1000000)),
                ('short_link', models.CharField(max_length=1000000)),
            ],
        ),
    ]
